### ISSUE TITLE
Ch 9 relative URLs

### ISSUE THREAD

**Issue by Amertz08** [leifos/tango_with_django_19#29]
Noticed a couple places where I think relative urls should of been used.
- pg 107
  - link back to homepage
  - action attribute on form
- pg 112
  - action attribute on form
- pg 113
  - link to login on `base.html`

**Comment by Amertz08** [comment]
Can send PR on this.

**Comment by maxwelld90** [comment]
Hey Adam,
Thanks for your comment and sorry for the delay in replying. Things have moved around a bit since you raised this. So the page numbers are probably a little out.

Page 107 (now 111 I believe) - the links are using the Django reverse lookup function. I think they are okay as is - maybe before they were written down statically?

For the second form (page 112, now 116) we again use the reverse lookup function. Do you mean to say that action should just be "."? I guess we could do that - but I would say it's better to be explicit. You could argue either way I guess.

I tweaked the last one - thanks for spotting that.

I'll leave this open if you want to comment!

Cheers,
David

**Comment by leifos** [comment]
We've gone through and tried... to fix all these..
